export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SET_LOGGED_IN = "SET_LOGGED_IN";

// export const GET_CURRENT_USER = "GET_CURRENT_USER";
// export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
// export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";
